### ISSUE TITLE
How to use gotoDate function to select arbitrary Date 

### ISSUE THREAD

**Issue by maheshtc** [thiagotalma/yii2-talma-fullcalendar-widget#10]
I have been using fullcalendar widget on my event listing page. I am listing events on selection of date. Events are correctly listed. But selected date not remain highlighted. I found that gotoDate is used to set arbitrary date. So How can I use in following code.

<?=  \talma\widgets\FullCalendar::widget([
                                'googleCalendar' => true,  // If the plugin displays a Google Calendar. Default false
                                'loading' => 'Loading...', // Text for loading alert. Default 'Loading...'
                                'config' => [
                                    'theme'=>true,
                                    'header'=>[
                                        'left'=>'prev',
                                        'center'=>'title',
                                        'right'=>'next'
                                    ],
                                    'height'=>'400',
                                    'themeCssFile'=>'cupertino/theme.css',
                                    'firstDay' => 1,
                                    'selectable' => true,
                                    'events' => array(),
                                    'dayClick' => new \yii\web\JsExpression('function(date, jsEvent, view) {
                                        var sdate = date.year()+"-"+(date.month()+1)+"-"+date.date();
                                        window.location.href="'.Url::to(['/events/']).'?date="+sdate;
                                    }'),
                                ],
                            ]);?>
Please suggest possible solution

**Comment by thiagotalma** [comment]
This is a question about the Fullcalendar, not this extension.
Please, go to Fullcalendar support.

**Comment by maheshtc** [comment]
Is it not a full calendar yii2 extension? I am using yii2-talma-fullcalendar-widget and I am need help in this.  If you are not using Fullcalendar then I will ask to fullcalendar support.

**Comment by thiagotalma** [comment]
This is only a wrapper for the Fullcalendar plugin.

Visit http://fullcalendar.io for any question about Fullcalendar functions.
Em 14/07/2015 02:54, "maheshtc" <notifications@github.com> escreveu:
