### ISSUE TITLE
Trying to load missing language file en-US.js

### ISSUE THREAD

**Issue by nterms** [thiagotalma/yii2-talma-fullcalendar-widget#6]
Widget tries to load the missing language file `en-US.js`. Default language of a Yii2 app is set to `en-US` and I noticed on line 58 of `FullCalendarAsset.php` it tries to load the language file based on the current application language. This results a file not found error on loading the page as there's no `en-US.js` file in `assets/lang` folder. So, perhaps the asset bundle should check whether the file exists before registering it with the bundle. Please fix this.

Thanks!

**Comment by thiagotalma** [comment]
The problem is that the script's default language is 'en', there is no language 'en-us'.
Fixed!
Thanks!

**Comment by nterms** [comment]
Thanks for the fix. Good work!
