### ISSUE TITLE
ReflectionException

### ISSUE THREAD

**Issue by kholmatov** [thiagotalma/yii2-talma-fullcalendar-widget#7]
Hi, i have some error:
===============================================================================
Class yii\jui\JuiAsset does not exist

    1. in /usr/share/nginx/www/advanced/vendor/yiisoft/yii2/di/Container.php at line 416
 */
        protected function getDependencies($class)
        {
            if (isset($this->_reflections[$class])) {
                return [$this->_reflections[$class], $this->_dependencies[$class]];
            }
     
            $dependencies = [];
            //print_r($class);
            $reflection = new ReflectionClass($class);
     
            $constructor = $reflection->getConstructor();
            if ($constructor !== null) {
                foreach ($constructor->getParameters() as $param) {
                    if ($param->isDefaultValueAvailable()) {
                        $dependencies[] = $param->getDefaultValue();
                    } else {
                        $c = $param->getClass();
                        $dependencies[] = Instance::of($c === null ? null : $c->getName());

**Comment by kholmatov** [comment]
In file <pre>[VandorDir]/thiagotalma/yii2-fullcalendar/widgets/FullCalendarAsset.php</pre> change <pre>public $depends = ['yii\jui\JuiAsset'];</pre> in to <pre>public $depends = ['yii\web\YiiAsset'];</pre>
work very well!

**Comment by philippfrenzel** [comment]
I don't think that's the reason...

**Comment by thiagotalma** [comment]
This change is not required.

Please check other error possibilities.

Apparently everything is okay with the extension.

**Comment by kholmatov** [comment]
ok, I will check!
