### ISSUE TITLE
How to Change UI-theme for fullcalendar-widget

### ISSUE THREAD

**Issue by maheshtc** [thiagotalma/yii2-talma-fullcalendar-widget#8]
I am trying to assign jquery ui theme UI Darkness, But I could not get it working. Please suggest how can I use ui theme

**Comment by philippfrenzel** [comment]
you have to set the theme attribute to true and then include the jquery - ui theme in your header....

**Comment by maheshtc** [comment]
Yes, I have set theme attribute to true and added jquery ui theme in theme directory. Now Its working. Is there any possibility to use it same like themeroller, where u can select any theme and it is applied to calendar?

**Comment by thiagotalma** [comment]
Thanks @philippfrenzel
